### ISSUE TITLE
convert_from_qiskit() does not handle complex parameter

### ISSUE THREAD

**Issue by JRGit4UE** [eclipse-qrisp/Qrisp#76] opened 2024-08-12 19:52 UTC
In my installed **Qrisp 0.4.9**  - and in **source code of 0.4.10** of `circuit_converter` function `convert_from_qiskit()`  starting at line 464 the loop over all params handle instances of type
* `ParameterExpression` and
* `(float, int)`

otherwise raises an `Exception: Could not convert parameter type {type(p)}`.
So, parameter of type `complex`  - in my case - e.g. complex= `(0.5+0j)` or `0j` are not handled.
I'm not sure if complex parameter with imag $\ne 0$ need a special treatment,
otherwise I would suggest to simply check `if isinstance(complex)` and `qrisp_params.append(p.real)`

**Comment by positr0nium** [comment] 2024-08-14 10:32
Hi,
could you get me a code example to reproduce? Which Qiskit gate has a complex parameter?

**Comment by positr0nium** [comment] 2024-08-14 15:19
It's fixed in https://github.com/eclipse-qrisp/Qrisp/commit/53ef4d2e1e93f2ec089fc6ca05c2216700c8c284 :)
Do you need help with installing the GitHub version?

**Comment by JRGit4UE** [comment] 2024-08-14 16:54
Thank you for the quick fix - I have updated to 0.4.10.

**Comment by JRGit4UE** [comment] 2024-08-14 17:33
When I compare the circuit depths of both versions - **qrisp** and **qiskit** in the code snippet above via
```python
qrisp_circuit = qrisp_QuantumCircuit.from_qiskit(qc)  # exception in circuit_converter.convert_from_qiskit()
qct = qrisp_circuit.transpile()
print(qc.depth(), 'vs.', qct.depth(), 'vs.', qrisp_circuit.depth())
```
I get `8 vs. 20 vs. 20` which comes from a single `Initialize()` gate in qiskit compared to the 11 (CX and R) gate layers in qrisp.
Is there a simple way to get to same value of depth 8 for the qrisp circuit as well?

**Comment by positr0nium** [comment] 2024-08-14 18:08
You see 8 because Qiskit is fooling you regarding that depth. It considers the initialize gate as depth 1 (even though it is certainly not). The way Qiskit measures depth is really useless (you could for instance wrap the whole circuit into a singular gate and you would have depth 1). The qrisp depth method always give you the transpiled depth but that it could still be argued that this is also a bit wonky.
A more solid measure is the qrisp_circuit.cnot_depth() method. Because CNOT gates are the prime bottleneck in NISQ devices, this will give you a good estimate on the speed of your circuit. If you have information about the particular gate speed of your backend you can also determine the precise time your circuit would run. For this check the depth_indicator feature here: https://www.qrisp.eu/reference/Circuit%20Construction/generated/qrisp.QuantumCircuit.depth.html#qrisp.QuantumCircuit.depth

**Closed** 2024-08-29 10:47 UTC
